# Generated by Django 4.0.4 on 2022-05-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('passward', models.CharField(max_length=50)),
                ('memo', models.CharField(max_length=300)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'group',
            },
        ),
    ]
